# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 01:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newswire.models
import paintstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=1200)),
                ('color', paintstore.fields.ColorPickerField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_start', models.DateField(default=datetime.datetime.now)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('text', models.TextField(blank=True, default=b'')),
                ('service_name', models.CharField(choices=[(b'sunday-morning-english', b'Sunday Morning - English Service'), (b'sunday-morning-chinese', b'Sunday Morning - Chinese Service')], default=b'sunday-morning-english', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=200)),
                ('body', models.TextField(default=b'', max_length=1200)),
                ('publish_start_date', models.DateField(default=datetime.datetime.now, verbose_name=b'Date to start publishing')),
                ('publish_end_date', models.DateField(default=newswire.models.get_default_publish_end_date, verbose_name=b'Date to end publishing')),
                ('link', models.CharField(blank=True, default=b'', max_length=400)),
                ('hidden', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, default=b'', max_length=200)),
                ('category', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='newswire.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ReadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40)),
                ('value', models.CharField(db_index=True, max_length=160)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unsubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('attendance', models.SmallIntegerField(blank=True, default=b'')),
                ('tithe_amt', models.DecimalField(blank=True, decimal_places=2, default=b'', max_digits=8)),
                ('building_amt', models.DecimalField(blank=True, decimal_places=2, default=b'', max_digits=8)),
                ('building_pledge_form_amt', models.DecimalField(blank=True, decimal_places=2, default=b'', max_digits=8)),
                ('monthly_loan_servicing_amt', models.DecimalField(blank=True, decimal_places=2, default=b'', max_digits=8)),
                ('c1_title', models.CharField(blank=True, max_length=200, null=True)),
                ('c1_amt', models.DecimalField(blank=True, decimal_places=2, default=b'', max_digits=8)),
                ('c2_title', models.CharField(blank=True, max_length=200, null=True)),
                ('c2_amt', models.DecimalField(blank=True, decimal_places=2, default=b'', max_digits=8)),
                ('c3_title', models.CharField(blank=True, max_length=200, null=True)),
                ('c3_amt', models.DecimalField(blank=True, decimal_places=2, default=b'', max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'weekly summaries',
            },
        ),
    ]
