# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Maiden Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefered_name',
            field=models.CharField(blank=True, help_text='We will use this name around the site instead of a combination of last+first name.', max_length=120, null=True, verbose_name='Preferred Name'),
        ),
    ]
