# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0002_auto_20161011_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group_profile', to='auth.Group'),
        ),
    ]
