# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0003_auto_20160511_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
