# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 20:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0004_auto_20160511_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_record_created',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_record_updated',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
