# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0004_auto_20161011_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.AddField(
            model_name='event',
            name='display_override',
            field=models.CharField(choices=[('hide', 'Hide'), ('show', 'Show')], default='hide', max_length=30),
        ),
    ]
