# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0008_auto_20160728_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
