# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0008_extendedgroup_individualattendance_individualgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndividualAttendance',
            new_name='GroupAttendance',
        ),
        migrations.RemoveField(
            model_name='individualgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='individualgroup',
            name='person',
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='leader',
            field=models.ManyToManyField(blank=True, related_name='leader_profile', to='newswire.Profile'),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='leader_member', to='newswire.Profile'),
        ),
        migrations.AlterField(
            model_name='extendedgroup',
            name='meeting_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'Irregular')], help_text='Day of the week the group regularly meets if any', null=True),
        ),
        migrations.AlterField(
            model_name='extendedgroup',
            name='meeting_time',
            field=models.TimeField(blank=True, help_text='Meeting time of the the group in 24hr format ie. 13:00 for 1pm', null=True),
        ),
        migrations.DeleteModel(
            name='IndividualGroup',
        ),
    ]
