# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0012_auto_20160915_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='under_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sundayattendance',
            name='under_review',
            field=models.BooleanField(default=True),
        ),
    ]
