# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0016_auto_20160923_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='approver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='submitter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sundayattendance',
            name='approver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sundayattendance',
            name='submitter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance_submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
