# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-29 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0017_auto_20160923_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_record_updated',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'm', b'Male'), (b'f', b'Female')], default=b'M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_profile', to='newswire.Group'),
        ),
    ]
