# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-29 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0018_auto_20160929_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group_profile', to='newswire.Group'),
        ),
    ]
