# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-29 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newswire', '0019_auto_20160929_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='member',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_relationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
