version: '2'
services:
  nginx:
    restart: always
    build: ./gbm-nginx/
    depends_on:
      - website
      - bulletin
    volumes:
      - /www/static
      - /var/www
    volumes_from:
      - website
      - bulletin
      - bulletin-static
    links:
      - bulletin:bulletin
    ports:
      - "80:80"

  website:
    build: ./gbm-website/
    command: >
             --destination="/var/www"
    volumes:
      - /var/www

  bulletin:
    restart: always
    build: ./gbm-bulletin/
    depends_on:
      - bulletin-postgres
      - bulletin-static
      - bulletin-redis
    expose:
      - "8000"
    depends_on:
        - bulletin-postgres
        - bulletin-redis
    links:
      - bulletin-postgres
      - bulletin-redis
    env_file: .env
    command: /usr/local/bin/gunicorn gbm.wsgi:application -w 2 -b :8000

  bulletin-static:
    build: ./gbm-bulletin/
    volumes:
      - /usr/src/app/static
    env_file: .env
    command: python manage.py collectstatic --noinput

  bulletin-postgres:
    restart: always
    image: postgres:latest
    volumes:
      - gbm-postgres:/var/lib/postgresql/data/pgdata
    env_file: .env
    ports:
      - "5432:5432"

  bulletin-redis:
    image: redis:latest

volumes:
  gbm-postgres:
