version: '2'

volumes:
  gbm-bulletin:
  gbm-postgres:
  bulletin-static:
  website:

services:

  nginx:
    restart: always
    build: ./gbm-nginx
    depends_on:
      - website
      - bulletin
      - bulletin-static
      - bulletin-postgres
    volumes:
      - website:/var/www/
      - bulletin-static:/usr/src/app/static
    links:
      - bulletin:bulletin
    ports:
      - "80:80"

  website:
    build: ./gbm-website
    command: >
             -v
             --destination="/var/www/"
    volumes:
      - website:/var/www/

  bulletin:
    environment:
      - DEBUG=TRUE
    restart: always
    build: ./gbm-bulletin
    depends_on:
      - bulletin-postgres
      - bulletin-static
      - bulletin-redis
    volumes:
      # Production
      - gbm-bulletin:/usr/src/app
      # Development
      #- ./gbm-bulletin/:/usr/src/app
      - bulletin-static:/usr/src/app/static
    expose:
      - "8000"
    depends_on:
        - bulletin-postgres
        - bulletin-static
        - bulletin-redis
    links:
      - bulletin-postgres
      - bulletin-redis
    env_file: .env
    command: /usr/local/bin/gunicorn gbm.wsgi:application -w 2 --reload -b :8000

  bulletin-static:
    build: ./gbm-bulletin
    volumes:
      - bulletin-static:/usr/src/app/static
    env_file: .env
    command: python manage.py collectstatic --noinput

  bulletin-postgres:
    restart: always
    image: postgres:9.5
    volumes:
      - gbm-postgres:/var/lib/postgresql/data/pgdata
    env_file: .env
    ports:
      - "5432:5432"

  bulletin-redis:
    image: redis:3.2-alpine
