#!/bin/bash

DATE=`date +%Y-%m-%d-%H-%M-%S`

case "$1" in
        start)
            docker-compose pull
            docker-compose build
            docker-compose up -d
            docker-compose ps
            ;;
        stop)
            docker-compose down
            docker-compose ps
            ;;
        restart)
            docker-compose down
            docker-compose pull
            docker-compose build
            docker-compose up -d
            docker-compose ps
            ;;
        rebuild)
            docker-compose down
            docker-compose pull
            docker-compose build --no-cache
            docker-compose up -d --force-recreate
            docker-compose ps
            ;;
        dev)
            docker-compose down
            docker-compose pull
            docker-compose build --no-cache
            docker-compose -f docker-compose.dev.yml up  --force-recreate -d
            docker-compose ps
            ;;
        status)
            docker-compose ps
            ;;
        clean)
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            ;;
        nuke)
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -a)
            docker volume rm $(docker volume ls |awk '{print $2}')
            ;;
        init)
            echo running migrations....
            docker-compose run --rm bulletin python manage.py migrate
            echo creating superuser
            docker-compose run --rm bulletin python manage.py createsuperuser --email admin@gbm.sg --username admin
            ;;
        migrate)
            docker-compose run --rm bulletin python manage.py makemigrations
            docker-compose run --rm bulletin python manage.py migrate
            ;;
        dump_live)
            #pg_dump -v -a -h gbm.sg -Fc -o -U postgres postgres > prod_db.$DATE.data.dump
            #pg_dump -v -s -h gbm.sg -Fc -o -U postgres postgres > prod_db.$DATE.schema.dump
            pg_dump -v -h gbm.sg -Fc -o -U postgres postgres > prod_db.$DATE.full.dump
            ;;
        *)
            echo $"Usage: $0 {start|stop|restart|rebuild|dev|status|clean|nuke|init|migrate|dump_live}"
            exit 1

esac
