# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newswire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('date_record_created', models.DateField(default=b'2000-01-01')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('date_of_baptism', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address_block', models.CharField(blank=True, max_length=12, null=True)),
                ('address_street', models.CharField(blank=True, max_length=140, null=True)),
                ('address_unit', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('is_regular', models.BooleanField(default=True)),
                ('is_member', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[(b'MO', b'Mother'), (b'FA', b'Father'), (b'BRO', b'Brother'), (b'SIS', b'Sister'), (b'SON', b'Son'), (b'DAUG', b'Daughter'), (b'GRMA', b'Grand Mother'), (b'GRFA', b'Grand Father'), (b'GRSON', b'Grand Son'), (b'GRDAUG', b'Grand Daughter')], max_length=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_relationship', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relationship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.CharField(choices=[(b'notgoing', b'Not Going'), (b'interested', b'Interested'), (b'going', b'Going')], default=b'notgoing', max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Announcement',
        ),
        migrations.RemoveField(
            model_name='readpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='readpost',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='track_rsvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='service_name',
            field=models.CharField(choices=[(b'sunday-morning-english', b'Sunday Morning - English Service')], default=b'sunday-morning-english', max_length=200),
        ),
        migrations.DeleteModel(
            name='ReadPost',
        ),
        migrations.AddField(
            model_name='signup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.Event'),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readannouncement',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.Announcement'),
        ),
        migrations.AddField(
            model_name='readannouncement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
