# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newswire', '0002_auto_20160510_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('prefered_name', models.CharField(blank=True, max_length=120, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=80, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('date_record_created', models.DateField(default=b'2000-01-01')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('date_of_baptism', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address_block', models.CharField(blank=True, max_length=12, null=True)),
                ('address_street', models.CharField(blank=True, max_length=140, null=True)),
                ('address_unit', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('is_regular', models.BooleanField(default=True)),
                ('is_member', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='member',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
