# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 03:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newswire', '0005_auto_20160614_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=b'0', max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'Date & Time of the metric')),
                ('notes', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DataSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[(b'ATTENDANCE', b'Attendance'), (b'FINANCIAL', b'Financial')], max_length=32)),
                ('owner', models.ManyToManyField(blank=True, default=b'', related_name='owner_dataseries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[(b'finance', b'Finance'), (b'management', b'Management'), (b'committee', b'Committee'), (b'ministry', b'Ministry'), (b'cg', b'Community Group')], max_length=32)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], default=b'M', max_length=1),
        ),
        migrations.AddField(
            model_name='dataseries',
            name='owner_group',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_group_dataseries', to='newswire.Group'),
        ),
        migrations.AddField(
            model_name='dataseries',
            name='viewer',
            field=models.ManyToManyField(blank=True, default=b'', related_name='viewer_dataseries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataseries',
            name='viewer_group',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_group_dataseries', to='newswire.Group'),
        ),
        migrations.AddField(
            model_name='data',
            name='dataseries',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='newswire.DataSeries'),
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to='newswire.Group'),
        ),
    ]
