# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0009_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2016, 9, 4, 7, 8, 49, 233934))),
                ('verse', models.TextField(default=b'', max_length=1200)),
                ('reference', models.CharField(default=b'', max_length=40)),
            ],
        ),
    ]
