# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import newswire.models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0010_weeklyverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('english_congregation', models.PositiveSmallIntegerField(default=0)),
                ('chinese_congregation', models.PositiveSmallIntegerField(default=0)),
                ('childrens_church', models.PositiveSmallIntegerField(default=0)),
                ('preschoolers', models.PositiveSmallIntegerField(default=0)),
                ('nursery', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeeklySummary',
        ),
        migrations.AddField(
            model_name='dataseries',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyverse',
            name='date',
            field=models.DateField(default=newswire.models.get_default_publish_end_date),
        ),
    ]
