# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import newswire.models


class Migration(migrations.Migration):

    dependencies = [
        ('newswire', '0010_weeklyverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseries',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyverse',
            name='date',
            field=models.DateField(default=newswire.models.get_default_publish_end_date),
        ),
    ]
