# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newswire', '0015_sundayattendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='dataseries',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataseries',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dataseries',
            name='owner_group',
        ),
        migrations.RemoveField(
            model_name='dataseries',
            name='viewer',
        ),
        migrations.RemoveField(
            model_name='dataseries',
            name='viewer_group',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sundayattendance',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_approver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_submitter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sundayattendance',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance_approver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sundayattendance',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance_submitter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.DeleteModel(
            name='DataSeries',
        ),
    ]
